apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: flask-mongodb
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: admin123secure
  mongo-username: flaskuser
  mongo-password: flaskpass123
