apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: flask-mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongo
  selector:
    app: mongo
  type: ClusterIP
---
# Headless service for StatefulSet DNS
apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  namespace: flask-mongo
  labels:
    app: mongo
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      name: mongo
  selector:
    app: mongo
