apiVersion: v1
kind: Secret
metadata:
  name: mongo-root-credentials
  namespace: flask-mongo
type: Opaque
stringData:
  # set these values or create via kubectl create secret
  mongo-root-username: root
  mongo-root-password: example123
